name: ML model Training

on:
  push:
    paths:
      - 'data/**'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Train the model
      run: python src/modeltraining.py

    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model/  #  Model is getting  saved here